import type { AppState } from './appState';

export interface SavedTemplate {
  id: string;
  name: string;
  type: 'cell' | 'organism';
  cellCount: number;
  roles: string[];
}

export const PRESET_LIBRARY_TEMPLATES: SavedTemplate[] = [
  {
    id: 'tpl-single-transport',
    name: 'Single Transport Cell',
    type: 'cell',
    cellCount: 1,
    roles: ['transport']
  },
  {
    id: 'tpl-single-feeder',
    name: 'Single Feeder Cell',
    type: 'cell',
    cellCount: 1,
    roles: ['feeder']
  },
  {
    id: 'tpl-dual-symbiont',
    name: 'Dual Symbiont Organism',
    type: 'organism',
    cellCount: 2,
    roles: ['transport', 'feeder']
  },
  {
    id: 'tpl-tri-colony',
    name: 'Tri-Cell Colony Organism',
    type: 'organism',
    cellCount: 3,
    roles: ['transport', 'feeder', 'sensor']
  }
];

export function validatePlacementCommand(
  x: number,
  y: number,
  worldWidth: number,
  worldHeight: number
): { valid: boolean; reason: string | null } {
  if (!Number.isFinite(x) || !Number.isFinite(y)) {
    return { valid: false, reason: 'Coordinates must be valid finite numbers' };
  }
  if (x < 0 || y < 0 || x > worldWidth || y > worldHeight) {
    return {
      valid: false,
      reason: `Coordinates (${x.toFixed(1)}, ${y.toFixed(1)}) exceed world boundaries (0..${worldWidth}, 0..${worldHeight})`
    };
  }
  return { valid: true, reason: null };
}

export function generateResearchReport(state: AppState): string {
  const frame = state.frame;
  const runId = frame.runId || 'N/A';
  const scenario = state.selectedScenarioId || 'N/A';
  const tick = frame.tick;
  const cellCount = frame.cells.length;
  const jointCount = frame.joints?.length ?? 0;
  const worldWidth = frame.world.width;
  const worldHeight = frame.world.height;
  const timestamp = new Date().toISOString();

  return `# ALife Research Experiment Report
**Generated:** ${timestamp}
**Run ID:** ${runId}
**Scenario ID:** ${scenario}
**Committed Tick:** ${tick}
**World Boundaries:** ${worldWidth} x ${worldHeight}

## 1. Simulation Population Summary
- **Total Active Cells:** ${cellCount}
- **Active Joint Connections:** ${jointCount}

## 2. Observer Provenance & Metadata
- **Source Context:** ${state.runnerEndpoint || 'http://127.0.0.1:8080'}
- **Data Completeness:** Bounded Live Frame Projection
- **Reproducibility Hash:** ${state.runStatus?.scenarioHash ?? 'N/A'}
- **Effective Seed:** ${state.runStatus?.effectiveSeed ?? 'N/A'}

---
*Report generated by ALife Control Center Research Export Tool (AL-007-S19).*
`;
}
