use std::path::Path;

#[test]
fn test_sweep_analyzer_generates_observer_files() {
    // Run sweep_analyzer binary with test configuration
    let mut cmd = std::process::Command::new("cargo");
    cmd.args([
        "run",
        "--bin",
        "sweep_analyzer",
        "--",
        "config/analyzer/sweep_analyzer_smoke.toml",
    ]);
    let status = cmd.status().unwrap();
    assert!(status.success());

    // Verify observer outputs exist (CSV, JSON, or MD reports)
    let behavior_csv = Path::new("outputs/raw_data/behavior_profiles.csv");
    let reports_dir = Path::new("outputs/reports");

    assert!(
        behavior_csv.exists() || reports_dir.exists(),
        "Observer files were not generated by sweep_analyzer"
    );
}

#[test]
fn test_sweep_analyzer_invalid_scenario_validation() {
    let invalid_toml = r#"
[run]
output_dir = "outputs/raw_data/smoke_invalid"
seed       = 42
ticks      = 10

[cell]
radius                    = 1.0
initial_energy            = 50.0
energy_capacity           = 100.0
mandatory_cost_per_tick   = 2.0
passive_energy_income     = 0.0
capacity_limit            = 30.0
initial_metabolic_material = 1.0
initial_transport_material = 1.0
initial_boundary_material  = 1.0
initial_structural_material= 1.0

[lifecycle]
stress_energy_threshold         = 10.0
dormancy_allowed                = true
dormant_mandatory_cost_modifier = 0.1
critical_capacity_overrun       = 5.0

[resource_interaction]
energy_per_resource              = 10.0
heat_per_resource                = 0.1
waste_per_resource               = 0.1
decay_rate                       = 0.01
default_resource_density         = 10.0
default_max_uptake_per_tick      = 1.0
default_metabolism_resource_per_tick = 0.5

[environment]
heat_dissipation_rate   = 0.2
heat_warning_threshold  = 50.0
heat_death_threshold    = 80.0
waste_sink_rate         = 0.1
waste_warning_threshold = 10.0
waste_death_threshold   = 20.0

[[sweep]]
name  = "finite_resource_viability"
scenario = "invalid_name_here"
param = "resource_density"
from  = 0.0
to    = 20.0
steps = 2
"#;

    let tmp_path = "target/test_invalid_config.toml";
    std::fs::create_dir_all("target").unwrap();
    std::fs::write(tmp_path, invalid_toml).unwrap();

    let mut cmd = std::process::Command::new("cargo");
    cmd.args(["run", "--bin", "sweep_analyzer", "--", tmp_path]);
    let status = cmd.status().unwrap();
    assert!(
        !status.success(),
        "Expected sweep_analyzer to fail with invalid scenario name"
    );
}
