use std::path::Path;

#[test]
fn test_sweep_analyzer_generates_observer_files() {
    // Run sweep_analyzer binary with test configuration
    let mut cmd = std::process::Command::new("cargo");
    cmd.args(&["run", "--bin", "sweep_analyzer", "--", "sweep_analyzer_smoke.toml"]);
    let status = cmd.status().unwrap();
    assert!(status.success());

    // Verify observer outputs exist (CSV, JSON, or MD reports)
    let behavior_csv = Path::new("outputs/raw_data/behavior_profiles.csv");
    let reports_dir = Path::new("outputs/reports");
    
    assert!(behavior_csv.exists() || reports_dir.exists(), "Observer files were not generated by sweep_analyzer");
}
