pub const CORE_MODULE_NAME: &str = "alife-core";

pub mod accounting;
pub mod cell_store;
pub mod config;
pub mod contact;
pub mod deltas;
pub mod environment;
pub mod events;
pub mod fragments;
pub mod genome;
pub mod heat;
pub mod ids;
pub mod joints;
pub mod lifecycle;
pub mod material_types;
pub mod materials;
pub mod process;
pub mod reactions;
pub mod resource_types;
pub mod resources;
pub mod snapshot;
pub mod spatial;
pub mod summary;
pub mod tick;
pub mod units;
pub mod world;
